name: Commit Logger

on:
  push:
    branches:
      - '*'

jobs:
  commit_logger:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create or append to user-specific file
      run: |
        user_file="user-${GITHUB_ACTOR}-pr-id.txt"
        echo "Commit ID: $GITHUB_SHA" >> $user_file
        echo "Author: $GITHUB_ACTOR" >> $user_file
        echo "Commit Message: ${{ github.event.head_commit.message }}" >> $user_file
        echo "Date: $(date)" >> $user_file

    - name: Commit and push changes
      run: |
        git config --local user.email "shivamnaik6574@gmail.com"
        git config --local user.name "shivamnaik6574"
        git add user-*.txt
        git commit -m "Add commit information"
        git push
